routes/web.php
<?php

use App\Http\Controllers\MessageController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'UserController@profile')->name('profile');
Route::post('update/user/{id}', 'UserController@update')->name('user-update');
Route::resource('user', 'UserController');
Route::resource('event', 'EventController');
Route::get('future/event', 'EventController@new')->name('event.new');
Route::get('past/event', 'EventController@past')->name('event.past');
Route::get('messages/{id}', 'MessageController@showMessage')->name('messages');
Route::post('send/message', 'MessageController@sendMessage')->name('send.message');
Route::post('user/{id}', 'UserController@deleteUser')->name('deleteUser');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = ['name', 'date' , 'description', 'image'];
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Redirect::back();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function new()
    {
        $now = now();
        $events = Event::whereDate('date','>=', $now)->orderBy('id', 'DESC')->paginate(3);
        return view('events.new_events', compact('events'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function past()
    {
        $now = now();
        $events = Event::whereDate('date','<', $now)->orderBy('id', 'DESC')->paginate(3);
        return view('events.past_events', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('events.create_event');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        if ($request->hasFile('image')) {
            $image      = $request->file('image');
            $fileName   = time() . '.' . $image->getClientOriginalExtension();
            $input['image'] = $fileName;
            $image->storeAs('public/images', $fileName);
        }
        
        unset($input['submit']);
        unset($input['_token']);
        $event = Event::create($input);

        if($event)
        {
            $status = "Event Created Successfully";
            return redirect('future/event')->with('status', $status);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = Event::findOrFail($id);
        return view('events.event', compact('event'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/events/create_event.blade.php
@extends('layouts.sidebar')

@section('dashboard')
<div class="container">
    <style>
        .upload {
            position: relative;
            overflow: hidden;
        }

        .upload>input {
            position: absolute;
            font-size: 50px;
            opacity: 0;
            right: 0;
            top: 0;
        }
    </style>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create Event</div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    @isset($status)
                        <div id="msg" class="alert alert-success" role="alert">
                            {{ $status }}
                        </div>
                    @endisset
                    <form action="{{route('event.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="offset-md-3"></div>
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label for="name">Event Name</label>
                                        <input type="text" class="form-control" name="name" autocomplete="off">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label for="date">Event Date</label>
                                        <input type="datetime-local" class="form-control" name="date" autocomplete="off">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label for="description">Description</label>
                                        <textarea name="description" class="form-control" cols="10" rows="3"></textarea>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <div class="col-md-5 btn btn-primary upload">
                                            Upload
                                            <input type="file" name="image" class="form-control-file">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-12">
                                        <input type="submit" value="Create Event" class="btn btn-success" name="submit">
                                    </div>
                                </div>
                            </div>
                            <div class="offset-md-3"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $(".alert-success").fadeOut(3000);
    });
</script>
@endsection

resources/views/events/event.blade.php
@extends('layouts.sidebar')

@section('dashboard')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ $event->name}}</div>

                <div class="card-body">
                    
                    <div class="container">
                        <a href="{{url()->previous()}}" class="btn btn-primary">Go Back</a> <br><br>
                        <div class="row">
                            <div class="col-md-12">
                                <img src="@if($event->image){{ '../storage/images/'.$event->image }}@else{{ asset('img/no-image.jpg') }}@endif" style="height:200px" alt="" class="img-fluid">
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md-12">
                                <h1>{{ $event->name}}</h1>
                                <p>{{$event->date}}</p>
                                <p>{{ $event->description}}</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/events/new_events.blade.php
@extends('layouts.sidebar')

@section('dashboard')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Future Events</div>

                <div class="card-body">
                    <div class="container">
                        @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                        @endif
                        <div class="row">
                            <div class="col-md-12">
                                <a href="{{route('event.create')}}" class="btn btn-primary">Create Event</a>
                                <br>
                                <br>
                                @foreach ($events as $event)
                                    <div class="row g-0">
                                        <a href="{{ route('event.show', $event->id)}}" style="display: inherit; color: black;">
                                            <div class="col-md-3">
                                                <img src="@if($event->image){{ '../storage/images/'.$event->image }}@else{{ asset('img/no-image.jpg') }}@endif" alt="..." class="img-fluid">
                                            </div>
                                            <div class="col-md-9">
                                                <div class="card-body">
                                                    <h5 class="card-title">{{$event->name}}</h5>
                                                    <p class="card-text">{{$event->date}}</p>
                                                    <p class="card-text">{{$event->description}}</p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <hr>
                                @endforeach
                            </div>
                        </div>
                        <div class="d-flex justify-content-center">
                            {!! $events->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>   
    <script>
        $(document).ready(function(){
            $(".alert-success").fadeOut(3000);
        });
    </script>
@endsection
   

resources/views/events/past_events.blade.php
@extends('layouts.sidebar')

@section('dashboard')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Past Events</div>

                <div class="card-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="{{route('event.create')}}" class="btn btn-primary">Create Event</a>
                                <br>
                                <br>
                                @foreach ($events as $event)
                                    <div class="row g-0">
                                        <a href="{{ route('event.show', $event->id)}}" style="display: inherit; color: black;">
                                            <div class="col-md-3">
                                                <img src="@if($event->image){{ '../storage/images/'.$event->image }}@else{{ asset('img/no-image.jpg') }}@endif" alt="..." class="img-fluid">
                                            </div>
                                            <div class="col-md-9">
                                                <div class="card-body">
                                                    <h5 class="card-title">{{$event->name}}</h5>
                                                    <p class="card-text">{{$event->date}}</p>
                                                    <p class="card-text">{{$event->description}}</p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <hr>
                                @endforeach
                            </div>
                        </div>
                        <div class="d-flex justify-content-center">
                            {!! $events->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>   
@endsection
   